# The documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  # For `pyproject.toml`
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"

  # For `.github/deps/latest/requirements.txt`, used in GitHub Actions
  - package-ecosystem: "pip"
    directory: "/.github/deps/latest"
    schedule:
      interval: "daily"

  # Note: `.github/deps/minimum/requirements.txt` is not updated by Dependabot.

  #
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
