name: Run unit tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: unit-test-${{ github.ref }}
  cancel-in-progress: true

env:
  PYTHONUNBUFFERED: "1"
  FORCE_COLOR: "1"
  PIP_PROGRESS_BAR: "off"

jobs:
  run:
    name: >
      Python ${{ matrix.python-version }} on
      ${{ startsWith(matrix.os, 'macos-') && 'macOS' || 'Linux' }}
      with ${{ matrix.deps }} dependencies
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        deps: [default, latest, minimum]
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14"]

    steps:
      - uses: actions/checkout@v5

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install packages
        if: matrix.deps == 'default'
        run: |
          pip install --upgrade pip
          pip install -e . --group tests
      
      - name: Install packages (latest)
        # Latest versions of dependencies monitored by Dependabot
        if: matrix.deps == 'latest'
        run: |
          pip install --upgrade pip
          pip install -e .
          pip install -r .github/deps/latest/requirements.txt
        
      - name: Install packages (minimum)
        # Oldest supported versions of dependencies in `pyproject.toml`
        if: matrix.deps == 'minimum'
        run: |
          pip install -e .
          pip install -r .github/deps/minimum/requirements.txt
      
      - name: List installed packages
        run: pip list

      - name: Run tests
        run: pytest -vv --cov --cov-report=xml

      - name: Check Codecov token # e.g., Dependabot doesn't have the CODECOV_TOKEN
        id: check_codecov_token
        run: |
          if [ -n "${{ secrets.CODECOV_TOKEN }}" ]; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Upload coverage to Codecov
        if: steps.check_codecov_token.outputs.exists == 'true'
        uses: codecov/codecov-action@v5
        with:
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true
